// Generated by Anvil v0.1 — All invariants verified at compile time.
// Zero runtime assertions needed. Trust is proven, not assumed.

fn main() {
    let s = transfer(100, 0, 50);
    let t = liquidate(1000, 100, 50, 0);
    println!("{} {}", s, t);
}

/// Verified invariants (5 proven):
/// #1: amount > 0
/// #2: sender_balance ≥ amount
/// #3: (sender_balance' + receiver_balance' = sender_balance + receiver_balance)
/// #4: sender_balance' = (sender_balance - amount)
/// #5: receiver_balance' = (receiver_balance + amount)
fn transfer(sender_balance: u64, receiver_balance: u64, amount: u64) -> u64 {
    let mut s = sender_balance;
    let mut r = receiver_balance;
    s -= amount;
    r += amount;
    let _ = r;
    s
}

/// Verified invariants (6 proven):
/// #1: repay_amount > 0
/// #2: close_factor > 0
/// #3: close_factor ≤ 100
/// #4: debt > 0
/// #5: total_repaid' ≤ ((debt × close_factor) ÷ 100)
/// #6: repay_amount ≤ (((debt × close_factor) ÷ 100) - total_repaid)
fn liquidate(_debt: u64, repay_amount: u64, _close_factor: u64, total_repaid: u64) -> u64 {
    let mut tr = total_repaid;
    tr += repay_amount;
    tr
}
